#!/usr/bin/env ruby

require 'erubis'
require 'active_support/inflector'
require 'method_source'

cfg = 'ServersmithFile'

if !File.exist?(cfg)
  puts "#{cfg} not found"
  exit(1)
end

class FieldDsl
  attr_reader :examples
  
  def initialize(name, type)
    @name = name
    @type = type
    @examples = []
  end

  def dbtype
    if @type == :string
      :string
    elsif @type == :integer
      :integer
    else
      :"userdef_#{@type}"
    end
  end

  def dbname
    @name
  end

end

class ResourceDsl
  attr_reader :fields, :flags, :triggers
  def initialize
    @fields = {}
    @flags = {
      deletable: false
    }
    @triggers = {}
  end

  def field(name, type, &block)
    raise "field name cannot start with underscore" if name.start_with?('_')
    name = name.to_s
    raise "Field #{name} already exist" if @fields.key?(name)

    f = FieldDsl.new(name, type)
    f.instance_eval(&block) if block
    @fields[name] = f
  end

  def example(name, exval)
    @fields[name.to_s].examples << exval
  end

  def set(flag)
    @flags[flag] = true
  end

  def on_create(&block)
    @triggers[:create] = {
      source: block.source.to_s.sub('on_create', 'blk = Proc.new')
    }
  end
end

class ServersmithFileDsl
  attr_reader :resources, :props
  def initialize
    @props = {
      package_name: 'base',
      package_authors: ['David Siaw'],
      package_emails: ['874280+davidsiaw@users.noreply.github.com'],
      package_homepage: 'https://github.com/davidsiaw/gem-base',
      package_license: 'MIT'
    }
    @resources = {}
  end

  def package_name(name)
    @props[:package_name] = name.to_s
  end

  def package_name_camelcase
    @props[:package_name].camelcase
  end

  def resource(name, &block)
    name = name.to_s
    raise "resource #{name} already exist" if @resources.key?(name)

    r = ResourceDsl.new
    r.instance_eval(&block)
    @resources[name] = r
  end
end

content = File.read(cfg)

ssf = ServersmithFileDsl.new
ssf.instance_eval(content, cfg)

class RzCodeGen
  attr_reader :dsl
  def initialize(ssdsl)
    @dsl = ssdsl
  end

  def generator_for(file, subsys)
    base_data_dir = File.join(Gem.loaded_specs['serversmith'].full_gem_path, 'data', 'serversmith', 'generators', subsys)
    template = File.join(base_data_dir, file)
    Erubis::Eruby.new(File.read(template), filename: template)
  end

  def generate_resources
    result = {}
    dsl.resources.each_with_index do |(resource_name, resource_info), idx|

      inf = {
        dsl: dsl,
        resource_name: resource_name,
        resource_info: resource_info
      }

      generator = generator_for('api.rb.erb', 'rz')

      result[".rz/app/apis/v1_api/#{resource_name}_api.rb"] = {
        content: generator.result(inf)
      }

      generator = generator_for('db.rb.erb', 'rz')

      result[".rz/db/migrate/30000101#{idx.to_s.rjust(6,'0')}_create_#{resource_name}.rb"] = {
        content: generator.result(inf)
      }

      generator = generator_for('model.rb.erb', 'rz')

      result[".rz/app/models/#{resource_name}.rb"] = {
        content: generator.result(inf)
      }

      generator = generator_for('job.rb.erb', 'rz')

      result[".rz/app/jobs/#{resource_name}_create_trigger_job.rb"] = {
        content: generator.result(inf)
      }

      generator = generator_for('api.rb.erb', 'gem')

      result[".gem/lib/#{dsl.props[:package_name]}/#{resource_name}.rb"] = {
        content: generator.result(inf)
      }

      generator = generator_for('api_spec.rb.erb', 'gem')

      result[".gem/spec/#{resource_name}_spec.rb"] = {
        content: generator.result(inf)
      }
    end
    result
  end

  def generate_root
    result = {}

    apilist = []

    dsl.resources.each do |resource_name, _|
      apilist << "    mount #{resource_name.to_s.camelize}Api"
    end

    generator = generator_for('main_api.rb.erb', 'rz')

    result[".rz/app/apis/main_api.rb"] = {
      content: generator.result({dsl: dsl})
    }

    `rm -rf .gem/lib/base`
    `rm -rf .gem/lib/base.rb`
    `rm -rf .gem/spec/base_spec.rb`
    `rm -rf .gem/*.gemspec`

    generator = generator_for('gemspec.rb.erb', 'gem')

    result[".gem/#{dsl.props[:package_name]}.gemspec"] = {
      content: generator.result({dsl: dsl})
    }

    `mkdir -p .gem/lib/#{dsl.props[:package_name]}`

    generator = generator_for('version.rb.erb', 'gem')

    result[".gem/lib/#{dsl.props[:package_name]}/version.rb"] = {
      content: generator.result({dsl: dsl})
    }

    generator = generator_for('base.rb.erb', 'gem')

    result[".gem/lib/#{dsl.props[:package_name]}.rb"] = {
      content: generator.result({dsl: dsl})
    }

    generator = generator_for('base_spec.rb.erb', 'gem')

    result[".gem/spec/#{dsl.props[:package_name]}_spec.rb"] = {
      content: generator.result({dsl: dsl})
    }

    generator = generator_for('client_spec.rb.erb', 'gem')

    result[".gem/spec/client_spec.rb"] = {
      content: generator.result({dsl: dsl})
    }

    generator = generator_for('spec_helper.rb.erb', 'gem')

    result[".gem/spec/spec_helper.rb"] = {
      content: generator.result({dsl: dsl})
    }

    generator = generator_for('README.md.erb', 'gem')

    result[".gem/README.md"] = {
      content: generator.result({dsl: dsl})
    }

    generator = generator_for('executable.erb', 'gem')

    result[".gem/exe/#{dsl.props[:package_name]}"] = {
      content: generator.result({dsl: dsl})
    }


    result
  end

  def generate
    result = {}

    generate_resources.each {|k,v| result[k]=v}
    generate_root.each {|k,v| result[k]=v}

    result
  end

end

# r = RzCodeGen.new(ssf)
# p r.generate



class RailsZen
  def initialize
    if !Dir.exist?('.rz')
      puts "setting up rz"
      reset!
    end
  end

  def reset!(ssf)
    `rm -rf .rz`
    `git clone https://github.com/davidsiaw/rails-zen .rz`

    `rm -rf .gem`
    `git clone https://github.com/davidsiaw/gem-base .gem`

    `rm -rf .fe`
    `chino create serversmith_frontend`
    `mv serversmith_frontend .fe`
  end

  def start!(ssf)
    `cd .rz && `
  end

  def apply!(ssf)
    rz = RzCodeGen.new(ssf)
    rz.generate.each do |filename, info|
      File.write("#{filename}", info[:content])
    end
  end
end




rz = RailsZen.new

rz.send("#{ARGV[0]}!", ssf)

# rz.reset!
# rz.apply(ssf)
